# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(dials)
    library(dplyr)
    library(parsnip)
    library(purrr)
    library(recipes)
    library(rlang)
    library(rsample)
    library(stats)
    library(themis)
    library(tibble)
    library(tidyr)
    library(tune)
    library(vctrs)
    library(workflows)
    library(yardstick)
}
b <- board_folder(path = "/var/folders/dj/kl17vwmx4qd13l4byj3kbmd80000gq/T/Rtmpu7qs5y/pins-70df52be8269")
v <- vetiver_pin_read(b, "logistic_regression_model", version = "20221004T143016Z-1e193")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
